### ISSUE TITLE
New Version New Save?

### ISSUE THREAD

**Issue by Enrory** [JulianR0/CLevels#3]
Sounds good but i lost all my points if i add new plugin. 
Is it possible to update version and stay xp/points? 

btw i like this plugin 
good job :)

**Comment by JulianR0** [comment]
I will try to build a tool to update old save formats to the new one. Let me see what I can do.

**Comment by JulianR0** [comment]
It's 4 AM here, so hopefully I didn't miss anything.

I built a simple tool on Python to convert all save files from the old v3.14 version to the newer v3.20 one.

[The tool is here.](https://github.com/JulianR0/CLevels/blob/v3/tools/converter.py)

Put the file on **svencoop/scripts/plugins/store/scxpm**. Then, in a terminal command, point to that folder and run the tool:

**python converter.py**
(Use python 3)

First time I use Python here. Make a backup of the store folder just in case.

**Comment by Enrory** [comment]
[scxpm.zip](https://github.com/JulianR0/CLevels/files/7149896/scxpm.zip)

thank you for your  fast work. 
I have tested but i get syntex error. Maybe i do something wrong. 
I send you my backup folder mybe you can convert it :)

**Comment by JulianR0** [comment]
I converted your files. Try this.

[scxpm_convert.zip](https://github.com/JulianR0/CLevels/files/7151409/scxpm_convert.zip)

**Comment by Enrory** [comment]
very big thanks 
all fine
