### ISSUE TITLE
No se guarda el progreso de achievements

### ISSUE THREAD

**Issue by neguma** [JulianR0/CLevels#4]
No sé si seguirás trabajando en este plugin pero ya no sé por donde más ver de qué forma arreglar esta función; los achievements funcionan, se completan correctamente y te otorga los premios como corresponde, pero al cambiar de mapa se borran y hay que desbloquearlos de nuevo... todo lo demás, niveles, configuración de hud, configuración de handicaps, todo se guarda correctamente, sólo los achievements no. Se genera el archivo "achievement-vault.ini" en /scripts/plugins/store/scxpm/achievement que creo que es el archivo donde se guarda la información de los logros de cada jugador, pero parecería que el plugin no lo lee a la hora de cargar los datos al cambiar de mapa, es una pena porque el plugin está excelente y es una bocanada de aire fresco por sobre el SCXPM clásico. Gracias de antemano.

**Comment by JulianR0** [comment]
Buenas. Gracias por el reporte.

Parece ser que accidentalmente agrege una regresion en una de las actualizaciones:
https://github.com/JulianR0/CLevels/blob/5a5eb815424b75c76bec5ed000edfa0d67b89311/src/SCXPM.as#L8481-L8483

Desactiva (comentar) las lineas 8482 y 8483 y vuelve a recompilar el plugin, los logros deberian guardarse ahora:
```c++
// Convert old v3.20/v3.21 to new save format
//g_AchievementVaultData[ iArraySize - 1 ].Replace( "_", "" );
//g_AchievementVaultData[ iArraySize - 1 ].Replace( "#", "" );
```

EDIT: Arreglado en v3.73 --> https://github.com/JulianR0/CLevels/commit/a702f46b9efd44d75531598b10da2001f717680d
Si no puedes editar el plugin tu mismo, puedes ahora descargar el plugin actualizado nuevamente.

**Comment by neguma** [comment]
Muchísimas gracias Julián, mañana lo testeo, gracias por la rápida respuesta y la preocupación. Me olvidé de mencionar otra cosa en el post original, que es que al subir de nivel y elegir una habilidad, el menú no se cierra una vez elegida la misma, hay que cerrarlo manualmente. Sin que tengas que tomarte la molestia de actualizar nuevamente el repo, esto es solucionable comentando alguna línea, o agregando alguna otra línea al código? Puedo modificarlo por mi cuenta. Gracias y te pido disculpas por las molestias.

**Comment by JulianR0** [comment]
> al subir de nivel y elegir una habilidad, el menú no se cierra una vez elegida la misma, hay que cerrarlo manualmente.

Esto es intencional. El SCXPM clasico conocido por todos muestra un mensaje en el chat (say) cada vez que se elije una habilidad. Esta version no tiene dicho mensaje, por lo que el menu se mantiene abierto para poder mostrarle al jugador que su seleccion fue confirmada.

No esta en mis planes agregar un mensaje de say (y cerrar el menu), pero puedes editarlo tu mismo: Lo que se encarga de asignar las habilidades se encuentra en la funcion `SCXPMSkillChoice`, empezando en la linea 5253. Despues de cada habilidad seleccionada, tienes que mostrar un mensaje, y luego tendras que comprobar el numero de `skillpoints` del jugador, de modo tal que solo se llame a la funcion `SCXPMSkill` (mediante el Scheduler) si aun tiene puntos de sobra pendientes de asignar.
