### ISSUE TITLE
Handicap Dirty Mag & Uzis dobles

### ISSUE THREAD

**Issue by neguma** [JulianR0/CLevels#5]
Hola, Julián! Quería reportarte que en la nueva versión de tu plugin, no se pueden recargar las uzis dobles si está activo el handicap nuevo, Dirty Mag, recarga sólo una de ellas, la segunda queda en 0 y por más que apretes el botón de recargar, no hace nada. De la única forma que se pueden recargar es usando el bug que tiene el SC de tirar una y agarrarla nuevamente cuando los cargadores de ambas están en 0.

Gracias!!

**Comment by JulianR0** [comment]
Gracias por el reporte.
Arreglado en v4.02 - https://github.com/JulianR0/CLevels/commit/dd1befe86cd8a155125dd65bf15e7b626328f47d

**Comment by neguma** [comment]
Testeado, funciona bien ahora, muchas gracias por el fix.
