### ISSUE TITLE
REQUEST: Custom Weapon Support for Ammo Regeneration Skill

### ISSUE THREAD

**Issue by Four-Ninez** [JulianR0/CLevels#7]
That would be very helpful, if it's possible of course. I tried to implement it myself, but I'm not very good at scripting.

**Comment by JulianR0** [comment]
I'm currently working on a future, v5 SCXPM update, that aims for easier customization. Adding custom weapons to ammo regeneration will be included and it will be easy to include new weapons.

**Comment by Four-Ninez** [comment]
Oh, I thought you had abandon working on this plugin, glad to see you're still working on it! I'll be looking forward to the update!
